# NeoBridge Authentication Service Configuration
spring:
  application:
    name: neobridge-auth-service
  
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/neobridge_dev
    username: neobridge_user
    password: neobridge_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      enable-idempotence: true
      compression-type: snappy
      linger-ms: 5
      request-timeout-ms: 30000

  # Mail Configuration (for verification emails)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:noreply@neobridge.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /auth

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:neobridge-jwt-secret-key-change-in-production}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  password:
    encoder:
      strength: 12

# Logging Configuration
logging:
  level:
    com.neobridge.auth: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: neobridge-auth-service
      environment: development

# OAuth2 Authorization Server Configuration
oauth2:
  authorization:
    server:
      client:
        registration:
          neobridge-web:
            client-id: neobridge-web-client
            client-secret: ${WEB_CLIENT_SECRET:web-client-secret}
            client-authentication-methods:
              - client_secret_basic
            authorization-grant-types:
              - authorization_code
              - refresh_token
            redirect-uris:
              - http://localhost:3000/callback
              - http://localhost:3001/callback
            scopes:
              - read
              - write
            client-settings:
              require-authorization-consent: false
              require-proof-key: false
          neobridge-mobile:
            client-id: neobridge-mobile-client
            client-secret: ${MOBILE_CLIENT_SECRET:mobile-client-secret}
            client-authentication-methods:
              - client_secret_post
            authorization-grant-types:
              - authorization_code
              - refresh_token
            redirect-uris:
              - com.neobridge.mobile://callback
            scopes:
              - read
              - write
            client-settings:
              require-authorization-consent: false
              require-proof-key: false

# Rate Limiting
rate-limit:
  login:
    max-attempts: 5
    window-duration: 900000 # 15 minutes
  registration:
    max-attempts: 3
    window-duration: 3600000 # 1 hour

# Feature Flags
features:
  two-factor-auth: true
  email-verification: true
  phone-verification: true
  social-login: false
  biometric-auth: false
