_format_version: "3.0"

services:
  # Test Service (existing)
  - name: test-service
    url: http://test-service.neobridge.svc.cluster.local:80
    routes:
      - name: test-route
        protocols:
          - http
        methods:
          - GET
        paths:
          - /
        strip_path: false

  # NeoBridge Common Service
  - name: neobridge-common
    url: http://neobridge-common.neobridge.svc.cluster.local:8080
    routes:
      - name: common-route
        protocols:
          - http
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        paths:
          - /common
          - /common/
        strip_path: true

  # NeoBridge Auth Service
  - name: neobridge-auth
    url: http://neobridge-auth.neobridge.svc.cluster.local:8081
    routes:
      - name: auth-route
        protocols:
          - http
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        paths:
          - /auth
          - /auth/
          - /oauth
          - /oauth/
        strip_path: true

  # NeoBridge Account Service
  - name: neobridge-account
    url: http://neobridge-account.neobridge.svc.cluster.local:8082
    routes:
      - name: account-route
        protocols:
          - http
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        paths:
          - /accounts
          - /accounts/
          - /account
          - /account/
        strip_path: true

  # NeoBridge Payment Service
  - name: neobridge-payment
    url: http://neobridge-payment.neobridge.svc.cluster.local:8083
    routes:
      - name: payment-route
        protocols:
          - http
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        paths:
          - /payments
          - /payments/
          - /payment
          - /payment/
        strip_path: true

  # NeoBridge Crypto Service
  - name: neobridge-crypto
    url: http://neobridge-crypto.neobridge.svc.cluster.local:8084
    routes:
      - name: crypto-route
        protocols:
          - http
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        paths:
          - /crypto
          - /crypto/
          - /wallet
          - /wallet/
        strip_path: true

  # NeoBridge AI Risk Service
  - name: neobridge-ai-risk
    url: http://neobridge-ai-risk.neobridge.svc.cluster.local:8085
    routes:
      - name: ai-risk-route
        protocols:
          - http
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        paths:
          - /ai-risk
          - /ai-risk/
          - /risk
          - /risk/
        strip_path: true

# Global plugins
plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Content-Type
        - Authorization
        - X-Requested-With
      exposed_headers:
        - X-Total-Count
      credentials: true
      max_age: 3600

  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      day: 10000
      policy: local

  - name: prometheus
    config:
      status_codes: true
      latency: true
      bandwidth: true
      upstream_health: true
