_format_version: "3.0"

services:
  - name: test-service
    url: http://test-service.neobridge.svc.cluster.local:80
    routes:
      - name: test-route
        protocols:
          - http
        methods:
          - GET
        paths:
          - /
        strip_path: false
