# NeoBridge API Gateway - Kong Alerting Rules
# Prometheus alerting rules for Kong API Gateway monitoring

groups:
  - name: kong-api-gateway
    rules:
      # High error rate
      - alert: KongHighErrorRate
        expr: rate(kong_http_requests_total{code=~"4..|5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "High error rate detected in Kong API Gateway"
          description: "Error rate is {{ $value }} errors per second for the last 5 minutes"

      # High latency
      - alert: KongHighLatency
        expr: histogram_quantile(0.95, rate(kong_http_request_duration_ms_bucket[5m])) > 1000
        for: 2m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "High latency detected in Kong API Gateway"
          description: "95th percentile latency is {{ $value }}ms for the last 5 minutes"

      # Service unavailable
      - alert: KongServiceUnavailable
        expr: up{job="kong"} == 0
        for: 1m
        labels:
          severity: critical
          service: kong
        annotations:
          summary: "Kong API Gateway is down"
          description: "Kong service has been down for more than 1 minute"

      # High request rate
      - alert: KongHighRequestRate
        expr: rate(kong_http_requests_total[5m]) > 1000
        for: 2m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "High request rate detected in Kong API Gateway"
          description: "Request rate is {{ $value }} requests per second for the last 5 minutes"

      # Rate limiting triggered
      - alert: KongRateLimitTriggered
        expr: increase(kong_ratelimiting_remaining[5m]) > 0
        for: 1m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "Rate limiting triggered in Kong API Gateway"
          description: "Rate limiting has been triggered for some clients"

      # JWT validation failures
      - alert: KongJWTValidationFailures
        expr: increase(kong_jwt_validation_failures_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "High JWT validation failure rate in Kong API Gateway"
          description: "{{ $value }} JWT validation failures in the last 5 minutes"

      # CORS violations
      - alert: KongCORSViolations
        expr: increase(kong_cors_violations_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "CORS violations detected in Kong API Gateway"
          description: "{{ $value }} CORS violations in the last 5 minutes"

      # Upstream service failures
      - alert: KongUpstreamServiceFailure
        expr: kong_upstream_health_checks_failed > 0
        for: 1m
        labels:
          severity: critical
          service: kong
        annotations:
          summary: "Upstream service health check failures in Kong API Gateway"
          description: "{{ $value }} upstream services are failing health checks"

      # Database connection issues
      - alert: KongDatabaseConnectionIssue
        expr: kong_database_connections_active > 80
        for: 2m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "High database connection count in Kong API Gateway"
          description: "{{ $value }} active database connections"

      # Memory usage high
      - alert: KongHighMemoryUsage
        expr: (kong_nginx_http_requests_total / kong_nginx_http_requests_total) * 100 > 80
        for: 2m
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "High memory usage in Kong API Gateway"
          description: "Memory usage is {{ $value }}%"

      # SSL certificate expiration
      - alert: KongSSLCertificateExpiring
        expr: kong_ssl_certificate_expiry_days < 30
        for: 1h
        labels:
          severity: warning
          service: kong
        annotations:
          summary: "SSL certificate expiring soon in Kong API Gateway"
          description: "SSL certificate expires in {{ $value }} days"

  - name: kong-database
    rules:
      # Database connection issues
      - alert: KongDatabaseDown
        expr: up{job="kong-database"} == 0
        for: 1m
        labels:
          severity: critical
          service: kong-database
        annotations:
          summary: "Kong database is down"
          description: "Kong database has been down for more than 1 minute"

      # High database connections
      - alert: KongDatabaseHighConnections
        expr: pg_stat_database_numbackends > 80
        for: 2m
        labels:
          severity: warning
          service: kong-database
        annotations:
          summary: "High database connection count"
          description: "{{ $value }} active database connections"

      # Slow queries
      - alert: KongDatabaseSlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname="kong"}[5m]) > 30
        for: 2m
        labels:
          severity: warning
          service: kong-database
        annotations:
          summary: "Slow database queries detected"
          description: "Queries taking longer than 30 seconds detected"

      # Disk space low
      - alert: KongDatabaseLowDiskSpace
        expr: node_filesystem_avail_bytes{mountpoint="/var/lib/postgresql"} / node_filesystem_size_bytes{mountpoint="/var/lib/postgresql"} < 0.1
        for: 5m
        labels:
          severity: critical
          service: kong-database
        annotations:
          summary: "Low disk space on Kong database"
          description: "Database disk space is below 10%"
