# NeoBridge API Gateway - Prometheus Configuration
# Monitoring configuration for Kong API Gateway

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'neobridge-api-gateway'

rule_files:
  - "kong-rules.yml"

scrape_configs:
  # Kong API Gateway metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: __address__
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}:8001'

  # Kong Database metrics (PostgreSQL)
  - job_name: 'kong-database'
    static_configs:
      - targets: ['kong-database:5432']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: __address__
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}:5432'

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    scrape_timeout: 5s

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Recording rules for Kong metrics
# Note: These rules will be defined in kong-rules.yml

# Storage configuration
# Note: Prometheus storage configuration is handled by Docker volumes
